### PR TITLE
fix: node opens index.js instead of running closes #15

### LINKED ISSUE #15: Node tries to open index.js, doesn't run it when running npx create...
@vltansky  I'm not sure how I ended up here, but in testing this I've seen two bugs. The first is that the folder argument doesn't seem to work, although I can no longer test _that_ as on two machines running any variation of the npx command opens index.js (in whatever app is associated with js files) and doesn't execute it.  I'm going to try to enlist some people to test this, but I'd at least like to understand how I got here before I open the floodgates.

### PR DESCRIPTION
**Pull request by vltansky**
closes #15

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1 +1,2 @@
+#!/usr/bin/env node
```
Comment (roblarsen) [inline index.js:1]: Ah, of course!

Comment (vltansky) [reply index.js:1]: My mistake :)
